### ISSUE TITLE
一个问题请教😄

### ISSUE THREAD

**Issue by defpis** [KaoriZh/KaoriZh#1]
hi，看了你的文章 https://www.cnblogs.com/Li-F/p/15187557.html 想请教一个问题：
最近在做文字渲染相关的工作，找到了一个直接在GPU上渲染矢量的方案 https://www.microsoft.com/en-us/research/wp-content/uploads/2005/01/p1000-loop.pdf 其中有一段不能理解
![image](https://user-images.githubusercontent.com/48018016/140455071-3e7a1cd1-8f2b-4511-bf48-8d9395e09694.png)
这里直接得到了 C(t) 属于 f(u,v) 的投影，始终没想通，你知道为什么吗？

**Comment by defpis** [comment]
选取的参数矩阵 F 也比较特别，如果选取不同，得到的隐式方程是否也不同呢？

**Comment by KaoriZh** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KaoriZh/KaoriZh"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月5日(星期五) 中午11:50
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[KaoriZh/KaoriZh] 一个问题请教😄 (Issue #1)





 
hi，看了你的文章 https://www.cnblogs.com/Li-F/p/15187557.html 想请教一个问题：
 最近在做文字渲染相关的工作，找到了一个直接在GPU上渲染矢量的方案 https://www.microsoft.com/en-us/research/wp-content/uploads/2005/01/p1000-loop.pdf 其中有一段不能理解
 
 这里直接得到了 C(t) 属于 f(u,v) 的投影，始终没想通，你知道为什么吗？
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by defpis** [comment]
@KaoriZh 大佬什么情况

**Comment by KaoriZh** [comment]
哦不好意思，我用托管邮箱回复了一张图片，乱码了，原文是这样的：

![image](https://user-images.githubusercontent.com/39049968/140724540-80fec339-33cf-4b4a-b9ce-ed2be175d8a8.png)

**Comment by defpis** [comment]
最不能理解的是截图的最后一句 “C(t) belongs to the transformed image of the curve f(u,v).” 只知道通过某个变换能从F到C，根本没办法把它们的隐式方程联系起来啊，这个是我最为困惑的😭

**Comment by defpis** [comment]
是不是其中隐含了射影几何的基本知识或者其他原因

**Comment by KaoriZh** [comment]
整个第2部分做了一些铺垫，简单来说，这里的参数形式其实就是单变量多项式基下的一个函数，采用基函数表示后，曲线实际上就只保留了一串相关的系数。由于研究的对象是二次曲线，只需二次多项式即可描述曲线，二次多项式包含三个基，对应的C矩阵也就是一个3x3的规模。其实这里可以直接用系数表示，但为了后续的变换，所以写成了等价的矩阵形式。

这里我直接采用代数方法分析了，涉及的是函数空间和变换的内容，射影几何我不太了解。
因为要证明的是曲线之间的对应关系，自然我们会往变换的方向去想，只要对任意曲线都能找出一个变换使两者对应，命题也就得证。为了能对任意曲线做变换，很自然的一个想法就是将其用某组基函数表示，基函数下的系数构成该函数空间的坐标，有了空间，就可以讨论变换了。而研究对象是有理二次曲线，那么选取多项式基是最便于证明的。

paper的第2.3小节也有提到关于“隐式曲线和参数曲线如何对应”的论文：
![image](https://user-images.githubusercontent.com/39049968/140782989-b6fa11e3-8d6f-4795-82d6-a3d9fc88cbae.png)
具体可以参考查阅。

**Comment by defpis** [comment]
查阅了论文中提到的隐式方程与参数方程相互转换的论文 https://www.researchgate.net/publication/220632467_Implicit_representation_of_parametric_curves_and_surfaces
其中运用到了消除理论，里面公式一大推，具体没看懂，所以来问问😄

**Comment by defpis** [comment]
总之还是很感谢你的回答👍🏻
